### ISSUE TITLE
[MSHARED-394] Avoid rewrite of destination in DefaultMavenFileFilter#filterFile when producing the same contents

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-filtering#202]
**[Vladimir Sitnikov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vlsi)** opened **[MSHARED-394](https://issues.apache.org/jira/browse/MSHARED-394?redirect=false)** and commented

See relevant MRESOURCES-168.

When processing "filtered" resources, maven-filtering always overwrites destination files, leading to rebuild of the upstream results (e.g. jar file being repackaged due to "DEBUG] isUp2date: false (Resource with newer modification date found.)").

I think maven-filtering can do better job here: it can double-check if the resource contents after filtering is equal to the contents of the existing file, then it should avoid overwrite of the destination file.

The change would be localized in `org.apache.maven.shared.filtering.DefaultMavenFileFilter#filterFile`:

```java
    private void filterFile(@Nonnull File from, @Nonnull File to, @Nullable String encoding, @Nullable List<FilterWrapper> wrappers) throws IOException, MavenFilteringException {
        if(wrappers != null && wrappers.size() > 0) {
            Reader fileReader = null;
            Writer fileWriter = null;

            try {
                fileReader = this.getFileReader(encoding, from);
                fileWriter = this.getFileWriter(encoding, to); // Here temporary buffer should be used to avoid accidental file overwrite
                Reader src = this.readerFilter.filter(fileReader, true, wrappers);
                IOUtil.copy(src, fileWriter);
            } finally {
                IOUtil.close(fileReader);
                IOUtil.close(fileWriter);
            }
        } else if(to.lastModified() < from.lastModified()) {
            FileUtils.copyFile(from, to);
        }

    }
```

The change would require to buffer the contents in memory, thus it might lead to OutOfMemory errors. I suggest disabling this buffering if the size of the source file exceeds some threshold.

---

**Affects:** maven-filtering-1.2

**Issue Links:**
- [MRESOURCES-168](https://issues.apache.org/jira/browse/MRESOURCES-168) Don't overwrite unchanged resource to prevent unnecessary subsequent processing
 (_**"is duplicated by"**_)
- [MASSEMBLY-734](https://issues.apache.org/jira/browse/MASSEMBLY-734) Control timestamps on archived files

- [MRESOURCES-168](https://issues.apache.org/jira/browse/MRESOURCES-168) Don't overwrite unchanged resource to prevent unnecessary subsequent processing
 (_**"is depended upon by"**_)

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

You may want to know that the latest version of maven-filtering/maven-archiver/plexus-archiver now actually supports rewriting of contents while retaining the exact attributes of the source file. This functionality is not entirely without side effects but we are now able to control this behaviour a lot closer than previously. This has to be changed in the client code in question, so does not /really/ need to be fixed in maven filtering. This feature is currently only implemented in assembly-plugin but "someone" might want to take a look at migrating this to other plugins.

Also note that all the details of this have not been ironed out entirely yet, see MASSEMBLY-734

**Comment by jira-importer** [comment]
**[Vladimir Sitnikov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vlsi)** commented

> This feature is currently only implemented in assembly-plugin but "someone" might want to take a look at migrating this to other plugins.

Can you please pin-point the API?

I still see no good reason why say "maven-assembly-plugin" should double-check the contents of resource "just in case the contents is equal".
Well, there might be ill-behaving plugins (including external to maven) that regenerate files for no reason, however, it is still an overhead to maven-assembly when it has to recheck the contents.

It would be better if well-known maven-resource-plugin would not regenerate the file in the first place.
It turns out, maven-resources-plugin relies on maven-filtering, thus there is nothing to fix in maven-resource-plugin itself.

Here's real life scenario:
Apache recommends the following parent.pom:

```xml
<parent>
  <groupId>org.apache</groupId>
  <artifactId>apache</artifactId>
  <version>14</version>
</parent>
```

This pom defines maven-resources-plugin that creates `DEPENDENCIES, LICENSE, NOTICE` files.
Due to "filtered files are always rewritten bug", maven-jar-plugin always rebuilds the jar.
This takes noticeable time and this impacts lots of projects that inherit this pom. It impacts other projects that use filtered resources as well.

The net effect is "maven is slow, just use gradle".

> This feature is currently only implemented in assembly-plugin but "someone" might want to take a look at migrating this to other plugins.
> Please clarify if you consider updating `DefaultMavenFileFilter#filterFile` a valid option.
> I guess I can figure out some pull request, however before I start the work I need to know if it has chances being committed.

From my point of view,
1) If maven-filtering must not be changed it would complicate client code with no significant reason
2) Updated `filterFile` would improve build times for all current plugin versions, while update of each "client" plugin would take a while
3) While having this feature implemented at different levels (in both maven-filtering, maven-jar, maven-assembly, etc) helps to cover more cases, I would suggest still cover the very basic case in maven-filtering as a quick-win.

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

I will need to think a little more about this problem. I dislike a comparison-based solution and would really try to come up with something better.

Please note that we currently do not compare content byte-for-byte like you suggest, but we have gotten amazingly much better at preserving file attributes, so much that this has also become a problem the other way around.

The code in question is org.apache.maven.plugin.assembly.format.ReaderFormatter#createReaderFilter which uses a MavenReaderFilter instead of a MavenFileFilter. The reader filter can be injected into plexus io as can be seen at org.apache.maven.plugin.assembly.archive.phase.FileItemAssemblyPhase#execute and various other places. But this code alone is by far not enough pieces to do what you want to do.

Personally I'm not interested in accepting "quick fixes", so I'd like any solution to be the best we can do at the moment. this may turn out to be your proposal - but hopefully there's something even better to be found; I just need to let this simmer for a few days...

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

Haven given this issue some thought I believe I have come up with a radically better solution than what is suggested here. There is no point in working on the changes suggested here, at least not until I give up my other plan.

Since I am currently working on a slightly different task, it will be a couple of weeks before I'll make any activity on this issue.

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

You make a compelling argument for a combined solution and basically use content-based copying/filtering for the velocity templates. If you want to have a shot at changing **just** the Velocity generation to use such an algorithm I'll happily review this; I want to do the interpolation stuff as a christmas hack :) If you you switch to using MavenReaderFilter instead of MavenFileFilter you should be able to solve such an issue entirely within resources-plugin. Take a look at ReaderFormatter.java in assembly plugin for inspiration.

DeferredFileOutputStream from commons-io would probably be a nice thing to use so you can keep the transformed output in memory until it reaches a given maxsize. I seem to remember we also use that in assembly :) If we need to move bits of your change elsewhere later we can look at this when you finish :)

I'm still pondering this a bit. One one hand we have a fixed set of templates that have known interpolation requirements. Rather than solving the general problem of "any" Velocity inteprolation, we could just solve the **specific** problem of interpolating the few specific ones we know to be used and delegate the "generic" problem elsewhere. So we might still be able to go for some kind of combined strategy.... (Thinking thinking...)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This issue has been auto closed because it has been inactive for a long period of time. If you think this issue still applies, retest your problem with the most recent version of Maven and the affected component, reopen and post your results.

**Comment by vlsi** [comment]
I think this is still relevant
